import type { CourseFormValues } from "./course-schema";
import { createId } from "@/lib/utils";

const emptyPricing = { price: 0, salePrice: 0, discount: 0 };

/** Default values for a fresh course (matches the form's reset state). */
export function makeDefaultCourseValues(): CourseFormValues {
  return {
    titleEn: "",
    titleAr: "",
    slug: "",
    category: "",
    difficulty: "Beginner",
    programType: "",
    attendanceMode: "online-zoom",
    headlineEn: "",
    headlineAr: "",
    subHeadlineEn: "",
    subHeadlineAr: "",
    descriptionEn: "",
    descriptionAr: "",
    previewVideoUrl: "",
    image: "",
    courseOverviewFile: "",
    brochureUrl: "",
    pricing: {
      egp: { ...emptyPricing },
      sar: { ...emptyPricing },
      usd: { ...emptyPricing },
    },
    students: 0,
    lectures: 0,
    duration: "",
    language: ["English"],
    instructorIds: [],
    tags: [],
    isActive: true,
    isFeatured: false,
    isBestseller: false,
    isTopRated: false,
    webhookUrl: "",
    seo: {
      metaTitleEn: "",
      metaTitleAr: "",
      metaDescriptionEn: "",
      metaDescriptionAr: "",
      metaKeywordsEn: [],
      metaKeywordsAr: [],
    },
    courseCode: "",
    educationalLevel: "",
    credentialAwardedEn: "",
    credentialAwardedAr: "",
    prerequisitesEn: "",
    prerequisitesAr: "",
    teachesEn: [],
    teachesAr: [],
    canonicalOverride: "",
    robotsDirective: "index,follow",
    ogImage: "",
    ogImageAlt: "",
    imageAltEn: "",
    imageAltAr: "",
    suppressBrandSuffix: false,
    intakes: [],
    proof: { passRate: 0, passRateBasisEn: "", passRateBasisAr: "", passRateVerifiedAt: "" },
    instructorProfile: {
      name: "", title: "", image: "", bio: "",
      yearsExperience: 0, hospitals: [], certifications: [], linkedIn: "",
    },
    whatYouWillLearnEn: [],
    whatYouWillLearnAr: [],
    whoCanAttendEn: "",
    whoCanAttendAr: "",
    whyChoose: [],
    faqs: [],
    careerRoles: [],
    relatedCourseSlugs: [],
    finalCta: { headingEn: "", headingAr: "", bodyEn: "", bodyAr: "" },
    quote: { textEn: "", textAr: "" },
    headings: { whyChooseEn: "", whyChooseAr: "", audienceEn: "", audienceAr: "", learnEn: "", learnAr: "", careersEn: "", careersAr: "", aboutEn: "", aboutAr: "", faqEn: "", faqAr: "" },
    modules: [
      {
        id: createId("mod"),
        titleEn: "Module 1: Introduction",
        titleAr: "",
        order: 0,
        lessons: [
          {
            id: createId("les"),
            lesson_type: "video",
            titleEn: "Welcome & Course Overview",
            titleAr: "",
            order: 0,
            isFreePreview: true,
          },
        ],
      },
    ],
    status: "draft",
    gallery: [],
    videosReviews: [],
    imagesReviews: [],
    textReviews: [],
  };
}
